# Uncomment the next line to define a global platform for your project

platform :macos, '10.13'

use_frameworks!

target 'Copy' do
	
	pod 'WCDB.swift'
  #pod 'KeyboardShortcuts'
  #pod 'Preferences'

end
